In [2]:
import numpy as np

In [4]:
x= np.array([1,2,3])

In [5]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [9]:
W = np.array([[1,2,3],[4,5,6]])

In [10]:
W.shape

(2, 3)

In [11]:
W.ndim

2

In [12]:
W = np.array ([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [13]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [14]:
A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])

In [16]:
b=np.array([10,20])

In [18]:
A*b


array([[10, 40],
       [30, 80]])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])