In [2]:
import numpy as np

In [4]:
x= np.array([1,2,3])

In [5]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [9]:
W = np.array([[1,2,3],[4,5,6]])

In [10]:
W.shape

(2, 3)

In [11]:
W.ndim

2

In [12]:
W = np.array ([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [13]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [14]:
A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])

In [16]:
b=np.array([10,20])

In [18]:
A*b


array([[10, 40],
       [30, 80]])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [21]:
import numpy as np


In [22]:
W1 = np.random.randn(2,4)

In [23]:
b1 = np.random.randn(4)


In [24]:
x = np.random.randn(10,2)

In [25]:
h = np.matmul(x,W1)+b1

In [26]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [27]:
a = sigmoid(h)

In [28]:
a

array([[0.51625354, 0.20601288, 0.1276323 , 0.15618641],
       [0.47667905, 0.09755021, 0.5142203 , 0.38251528],
       [0.28761674, 0.14142392, 0.39641795, 0.26030143],
       [0.52509712, 0.07644168, 0.62973538, 0.4713221 ],
       [0.13566573, 0.41048719, 0.04585585, 0.04688585],
       [0.11297382, 0.14256758, 0.54358068, 0.2617138 ],
       [0.44395345, 0.15889958, 0.25336657, 0.22356021],
       [0.04156008, 0.45174518, 0.06219661, 0.03837787],
       [0.02810347, 0.11950567, 0.80296171, 0.32483011],
       [0.52654314, 0.19548001, 0.14160808, 0.16836908]])

In [30]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

x=np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1

a=sigmoid(h)
s = np.matmul(a,W2) +b2

In [31]:
import numpy as np

class Sigmoid:
    def __init__(self):
        self.params=[]

    def forward(self,x):
        return 1 / (1+np.exp(-x))
        

In [32]:
class Affine:
    def __init__(self,W,b):
        self.params = [W,b]

    def forward(self, x):
        W, b = self.params
        out =np.matmul(x,W)+b
        return out

In [33]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        #가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H,O)
        b2 = np.random.randn(O)
    
        # 계층 새엇ㅇ
        self.layers = [Affine(W1,b1),
                      Sigmoid(),
                      Affine(W2,b2)
                      ]
    
        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x=layer.forward(x)
        return x
    

In [34]:
x = np.random.randn(10,2)

In [35]:
model = TwoLayerNet(2,4,3)

In [36]:
s = model.predict(x)

In [37]:
s

array([[ 2.18733084, -0.82581609,  2.59295556],
       [ 2.58300047, -0.65865095,  2.28621761],
       [ 2.43251538, -0.55330452,  2.39245704],
       [ 2.47196101, -0.82416857,  2.37050755],
       [ 2.22124995, -0.96115851,  1.6934006 ],
       [ 2.26599674, -0.41956991,  2.50277153],
       [ 1.95887782, -0.86437558,  2.77068703],
       [ 1.84314065, -0.9730633 ,  1.80167199],
       [ 2.56391621, -0.85066996,  2.29490477],
       [ 2.67113592, -0.56900986,  2.23159846]])